- [x] Diagnose all 3 subtitle providers failing (OS: dead API key, Subdl: 404, YIFY: movies-only)
- [x] Fix subtitle-freestream.ts - remove YIFY (movies only), fix Podnapisi parser
- [x] Fix subtitle-scraper.ts - fix Subdl URL format for TV shows
- [x] Cache CinePro waterfall subtitles for reuse by separate subtitle search
- [x] Modify resolveSubtitles.ts to check cache + use waterfall subtitles first
- [x] Remove dead OpenSubtitles dependency
- [x] Build + deploy
