import express from "express";
import cors from "cors";
import resolveRouter from "./routes/resolveStream.js";
import resolveSubtitlesRouter from "./routes/resolveSubtitles.js";
import proxyRouter from "./routes/proxyStream.js";
import persistentCache from "./cache.js";
const app = express();
const PORT = Number(process.env.PORT) || 3006;
app.use(cors());
app.use(express.json());
app.use("/api", resolveRouter);
app.use("/api", resolveSubtitlesRouter);
app.use("/api", proxyRouter);
app.get("/health", (_req, res) => { res.json({ status: "ok", timestamp: new Date().toISOString() }); });
app.get("/api/clear-cache", (_req, res) => {
  const before = persistentCache.stats();
  for (const key of before.keys) persistentCache.del(key);
  const after = persistentCache.stats();
  res.json({ success: true, message: "Cache cleared", cleared: before.keyCount, remaining: after.keyCount });
});
app.listen(PORT, () => { console.log("[ReelView Engine] Server on http://localhost:" + PORT); });
export default app;
